@extends('layouts.web')
@section('content')

  
    <header class="about-header" style="background-image: url('./media/{{config('custom.page_header_about')}}');;background-position: center;background-repeat: no-repeat;">
        <!--<h1 class="hf1">Get to Know us a little better</h1>-->
    </header>


    <div class="container about-container">
        <section class="mission">
            <div class="mission-title">
                <h1 class="hf2">DBF Satsang</h1>
            </div>
            <div class="bf mission-desc">
                We exist to Cultivate Christ centred Communities to Redeem Delhi & beyond for the glory of God                
            </div>
        </section>
        <svg id="bigTriangleColor" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100" viewBox="0 0 100 102" preserveAspectRatio="none">
            <path d="M0 0 L50 100 L100 0 Z" />
        </svg>

        <section class="beliefs">
            <div class="beliefs-title">
                <h2 class="hf2">Our Beliefs</h2>
            </div>
            <div class="beliefs-desc">
                <ul class="bf beliefs-list">
                    <li>We believe the Bible, both the Old & New Testaments, to be the inspired Word of God, without error in the original writing, the complete revelation of His will for the salvation of man and the absolute divine authority for all Christian faith, life and conduct.</li>
                    <li>We believe in one God, creator of all things, infinitely perfect and eternally existing in three persons, the Father, the Son & the Holy Spirit.</li>
                    <li>We believe Jesus Christ, without any change in His eternal Deity became man through conception by the Holy Spirit and virgin birth. He died on the cross, a perfect and complete sacrifice, in our stead and for our sins according to the Scriptures. He arose bodily from the dead, and ascended into heaven where having seated at the right hand of the Majesty on high, He is now our High Priest and advocate.</li>
                    <li>We believe that the ministry of the Holy Spirit is to glorify the Lord Jesus Christ and during this age to convict people of sin and regenerate them upon believing in Christ, at the time of regeneration baptising the believer into the one Body of which Christ is the head; and to indwell, guide, instruct, fill and empower the believer for godly living and service.</li>
                    <li>We believe that man was created by God in His own image, but fell into sin. The entire human race is, therefore, lost and only by God’s grace and through repentance and faith in Jesus Christ, and transforming work of the Holy Spirit, can salvation and spiritual life be obtained.</li>
                    <li>We believe that the atoning death of Jesus Christ, and His resurrection, provide the only ground of justification and salvation for all who believe, and that only such as receive Jesus Christ by personal faith are born of the Holy Spirit, and thus, become the children of God.</li>
                    <li>We believe in the personal, pre-millennial return of our Lord Jesus Christ, and that this blessed hope has a vital bearing on the personal life and service of the believer.</li>
                    <li>We believe in the bodily resurrection of all the dead, of the believer to everlasting blessedness and joy with the Lord, and the unbeliever to judgment and everlasting and conscious punishment.</li>
                    <li>We believe that the Church is composed of all such persons who through saving faith in Jesus Christ have been regenerated by the Holy Spirit and are united together in the Body of Christ, of which He is the Head.</li>
                    <li>We believe in practicing baptism by immersion upon profession of faith, understanding this to be the teaching of the New Testament, yet at the same time shall be free to admit into fellowship any Christian believer of godly walk and conversation who holds the faith and doctrine as herein set forth.</li>
                    <li>We believe that the ordinance of the Lord’s Supper should be observed regularly, preferably on the first Lord’s Day of each month, and shall be presided over by the Pastor or by any duly authorised person.</li>
                    <li>We believe that it is the privilege of Christian parents to present their children in dedication to the Lord before the church, that they may made the subject of united and solemn prayer.</li>
                    <li><br><br></li>
                    <li>We believe that all the saved should love in such a manner as will honour and glorify and not bring reproach upon their Saviour and Lord and that it is commended of God to remain separate from false doctrines, and sinful pleasures, practices and associations.</li>
                </ul>
            </div>
            <svg id="ABOUTbigTriangleColor" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100" viewBox="0 0 100 102" preserveAspectRatio="none">
                <path d="M0 0 L50 100 L100 0 Z" />
            </svg>
        </section>
        
        <section class="container gallery-container" style="background-color: #ffffff; margin-top:5%;background: none;">
             @foreach($images as $img)
                <section class="gallery-wrapper">
                        <div class="gallery-tile">
                            <img src="{{asset('images/'.$img->image)}}">
                            <div class="gallery-subtitle-overlay"><p>{{$img->title}}</p><div>
                        </div>
                </section>
            @endforeach
        </section>
        <svg id="ABOUTbigTriangleColor" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100" viewBox="0 0 100 102" preserveAspectRatio="none" style="background: white; ">
            <path d="M0 0 L50 100 L100 0 Z" />
        </svg>
    </div>
@endsection